### ISSUE TITLE
Bug in kiscollect

### ISSUE THREAD

**Issue by p0w1** [chopicalqui/KaliIntelligenceSuite#4]
I setup KIS using docker as explained here: https://hub.docker.com/r/chopicalqui/kali-intelligence-suite
As soon as I run kiscollect there is the following error (independent of added domains/ips/hostnames and collectors):

`
kis_shell> kismanage workspace -a test     
kis_shell> kismanage domain -w test -a asdfasdf.ch              
kis_shell> kiscollect -w test --dnsspf 
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/kaliintelsuite/kis/database/utils.py", line 84, in session_scope
    yield session
  File "/opt/kaliintelsuite/kis/collectors/os/collector.py", line 389, in init
    item.create_instance(engine=self._engine, **kwargs)
  File "/opt/kaliintelsuite/kis/collectors/os/collector.py", line 123, in create_instance
    self._instance = self._collector_class(name=self._arg_option, **kwargs)
  File "/opt/kaliintelsuite/kis/collectors/os/modules/dns/dnsspf.py", line 48, in __init__
    super().__init__(priority=215,
  File "/opt/kaliintelsuite/kis/collectors/os/modules/dns/core.py", line 70, in __init__
    super().__init__(priority=priority,
  File "/opt/kaliintelsuite/kis/collectors/os/modules/core.py", line 456, in __init__
    for item in filter:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/bin/kiscollect", line 422, in <module>
    producer.init(arguments)
  File "/opt/kaliintelsuite/kis/collectors/os/collector.py", line 389, in init
    item.create_instance(engine=self._engine, **kwargs)
  File "/opt/kaliintelsuite/kis/collectors/os/collector.py", line 123, in create_instance
    self._instance = self._collector_class(name=self._arg_option, **kwargs)
  File "/opt/kaliintelsuite/kis/collectors/os/modules/dns/dnsspf.py", line 48, in __init__
    super().__init__(priority=215,
  File "/opt/kaliintelsuite/kis/collectors/os/modules/dns/core.py", line 70, in __init__
    super().__init__(priority=priority,
  File "/opt/kaliintelsuite/kis/collectors/os/modules/core.py", line 456, in __init__
    for item in filter:
TypeError: 'NoneType' object is not iterable

`

**Comment by chopicalqui** [comment]
Hey @p0w1 

Thanks for your bug report. I fixed your reported bug already in branch main but did not publish a new Docker image yet because I am still writing unittests, fix bugs and update documentation.

If you want to use a working KIS Docker image, then I recommend building the Docker image on your own by following the instructions at:
https://github.com/chopicalqui/KaliIntelligenceSuite/blob/main/INSTALL.md#build-and-run-docker

I hope this helps.

Cheers

**Comment by chopicalqui** [comment]
Hey @p0w1

I pushed a new Docker image to [hub.docker.com](https://hub.docker.com/repository/docker/chopicalqui/kali-intelligence-suite), which, among other things, contains the fix for your reported bug.

Thanks for reporting.

Cheers
